#!/usr/bin/env bash
# Auto-generated by scripts/gen_reproduce.py — freegs experiments.
# Usage: bash scripts/reproduce_freegs.sh [run1 run2 ...]
#        (no args = run ALL experiments; run names from function list below)

set -e
export PYTHONPATH="$(cd "$(dirname "$0")/.." && pwd)/src${PYTHONPATH:+:$PYTHONPATH}"

run_freegs_rhs_planet() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_rhs_planet  (2026-07-07)

    echo "=== freegs_rhs_planet ==="
    python -m gs_pino.train_freegs \
    --hidden-dim 128 \
    --scale-mse 1 \
    --scale-pde 0.1 \
    --batch-size 8 \
    --accum-steps 1 \
    --no-amp \
    --lr 0.0005 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 50 \
    --clip-grad 1 \
    --seed 42 \
    --data 'data/freegs_rhs_500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_rhs_planet
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_rhs_planet/best.pt --data data/freegs_rhs_500.npz
}

run_freegs_test_rmse() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_test_rmse  (2026-07-07)

    echo "=== freegs_test_rmse ==="
    python -m gs_pino.train_freegs \
    --hidden-dim 128 \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0.01 \
    --scale-ip 0.001 \
    --batch-size 32 \
    --accum-steps 1 \
    --amp \
    --lr 0.001 \
    --warmup-epochs 1 \
    --epochs 2 \
    --min-epochs 1 \
    --patience 10 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_test_rmse
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_test_rmse/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_v9() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_v9  (2026-07-08)
    #  test: plasma rel L2 = 9.57% (psi_total: 0.00%)
    echo "=== freegs_planet_v9 ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0.01 \
    --scale-ip 0.001 \
    --scale-curvature 0.5 \
    --batch-size 8 \
    --accum-steps 4 \
    --amp \
    --lr 0.0005 \
    --warmup-epochs 10 \
    --epochs 300 \
    --min-epochs 100 \
    --patience 80 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_v9
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_v9/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_ufno_v2() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_ufno_v2  (2026-07-08)
    #  test: plasma rel L2 = 18.03% (psi_total: 0.00%)
    echo "=== freegs_ufno_v2 ==="
    python -m gs_pino.train_freegs \
    --model 'ufno' \
    --hidden-dim 256 \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0.01 \
    --scale-ip 0.001 \
    --scale-curvature 0.1 \
    --batch-size 8 \
    --accum-steps 4 \
    --no-amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 800 \
    --min-epochs 200 \
    --patience 150 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_ufno_v2
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_ufno_v2/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_ufno_mse() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_ufno_mse  (2026-07-08)
    #  test: plasma rel L2 = 10.02% (psi_total: 0.00%)
    echo "=== freegs_ufno_mse ==="
    python -m gs_pino.train_freegs \
    --model 'ufno' \
    --hidden-dim 256 \
    --scale-mse 1 \
    --scale-pde 0 \
    --scale-axis 0 \
    --scale-ip 0 \
    --scale-curvature 0 \
    --batch-size 8 \
    --accum-steps 4 \
    --no-amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 800 \
    --min-epochs 200 \
    --patience 100 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_ufno_mse
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_ufno_mse/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_plasma() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_plasma  (2026-07-08)  predict_plasma
    #  test: plasma rel L2 = 8.64% (psi_total: 10.57%)
    echo "=== freegs_planet_plasma ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --predict-plasma \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0.01 \
    --scale-ip 0.001 \
    --scale-curvature 0.1 \
    --batch-size 8 \
    --accum-steps 4 \
    --amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 100 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_plasma_mse() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_plasma_mse  (2026-07-08)  predict_plasma
    #  test: plasma rel L2 = 8.29% (psi_total: 10.19%)
    echo "=== freegs_planet_plasma_mse ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --predict-plasma \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0 \
    --scale-ip 0 \
    --scale-curvature 0 \
    --batch-size 8 \
    --accum-steps 4 \
    --amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 100 \
    --clip-grad 1 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_mse
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_mse/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_plasma_opt() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_plasma_opt  (2026-07-09)  predict_plasma
    #  test: plasma rel L2 = 7.55% (psi_total: 9.28%)
    echo "=== freegs_planet_plasma_opt ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --dropout 0.1 \
    --predict-plasma \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0.01 \
    --scale-ip 0.001 \
    --scale-curvature 0.01 \
    --batch-size 8 \
    --accum-steps 4 \
    --amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 100 \
    --weight-decay 0.0001 \
    --clip-grad 1 \
    --noise-std 0.05 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_opt
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_opt/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_plasma_coil() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_plasma_coil  (2026-07-09)  predict_plasma + use_coil_input
    #  test: plasma rel L2 = 6.89% (psi_total: 8.33%)
    echo "=== freegs_planet_plasma_coil ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --fourier-freqs 32 \
    --dropout 0.1 \
    --use-coil-input \
    --predict-plasma \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0 \
    --scale-ip 0 \
    --scale-curvature 0 \
    --batch-size 8 \
    --accum-steps 4 \
    --amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 100 \
    --weight-decay 0.0001 \
    --clip-grad 1 \
    --noise-std 0.05 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_coil
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_coil/best.pt --data data/freegs_merged_1500.npz
}

run_freegs_planet_plasma_soft() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\freegs_planet_plasma_soft  (2026-08-12)  predict_plasma + use_coil_input
    #  test: plasma rel L2 = 7.27% (psi_total: 8.81%)
    echo "=== freegs_planet_plasma_soft ==="
    python -m gs_pino.train_freegs \
    --model 'planet' \
    --hidden-dim 256 \
    --fourier-freqs 32 \
    --dropout 0.1 \
    --use-coil-input \
    --predict-plasma \
    --scale-mse 1 \
    --scale-pde 0.01 \
    --scale-axis 0 \
    --scale-ip 0 \
    --scale-curvature 0 \
    --batch-size 8 \
    --accum-steps 4 \
    --no-amp \
    --lr 0.0001 \
    --warmup-epochs 10 \
    --epochs 500 \
    --min-epochs 200 \
    --patience 100 \
    --weight-decay 0.0001 \
    --clip-grad 1 \
    --noise-std 0.05 \
    --seed 0 \
    --data 'data/freegs_merged_1500.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_soft
    python -m gs_pino.evaluate_freegs --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/freegs_planet_plasma_soft/best.pt --data data/freegs_merged_1500.npz
}

if [ $# -gt 0 ]; then
    for exp in "$@"; do
        case "$exp" in
            freegs_rhs_planet) run_freegs_rhs_planet ;;
            freegs_test_rmse) run_freegs_test_rmse ;;
            freegs_planet_v9) run_freegs_planet_v9 ;;
            freegs_ufno_v2) run_freegs_ufno_v2 ;;
            freegs_ufno_mse) run_freegs_ufno_mse ;;
            freegs_planet_plasma) run_freegs_planet_plasma ;;
            freegs_planet_plasma_mse) run_freegs_planet_plasma_mse ;;
            freegs_planet_plasma_opt) run_freegs_planet_plasma_opt ;;
            freegs_planet_plasma_coil) run_freegs_planet_plasma_coil ;;
            freegs_planet_plasma_soft) run_freegs_planet_plasma_soft ;;
            *) echo "unknown experiment: $exp"; echo "known: freegs_rhs_planet freegs_test_rmse freegs_planet_v9 freegs_ufno_v2 freegs_ufno_mse freegs_planet_plasma freegs_planet_plasma_mse freegs_planet_plasma_opt freegs_planet_plasma_coil freegs_planet_plasma_soft"; exit 1 ;;
        esac
    done
else
    run_freegs_rhs_planet
    run_freegs_test_rmse
    run_freegs_planet_v9
    run_freegs_ufno_v2
    run_freegs_ufno_mse
    run_freegs_planet_plasma
    run_freegs_planet_plasma_mse
    run_freegs_planet_plasma_opt
    run_freegs_planet_plasma_coil
    run_freegs_planet_plasma_soft
fi
