#!/usr/bin/env bash
# Auto-generated by scripts/gen_reproduce.py — fixed experiments.
# Usage: bash scripts/reproduce_freegs.sh [run1 run2 ...]
#        (no args = run ALL experiments; run names from function list below)

set -e
export PYTHONPATH="$(cd "$(dirname "$0")/.." && pwd)/src${PYTHONPATH:+:$PYTHONPATH}"

run_large() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\large  (2026-06-25)

    echo "=== large ==="
    python -m gs_pino.train \
    --modes1 32 \
    --modes2 32 \
    --width 64 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --seed 0 \
    --epochs 200 \
    --batch-size 16 \
    --lr 0.001 \
    --data 'data/gs_large.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large/best.pt --data data/gs_large.npz
}

run_large_v2() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\large_v2  (2026-06-25)

    echo "=== large_v2 ==="
    python -m gs_pino.train \
    --modes1 32 \
    --modes2 32 \
    --width 64 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --clip-grad 1 \
    --seed 0 \
    --epochs 200 \
    --batch-size 16 \
    --lr 0.001 \
    --data 'data/gs_large.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v2
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v2/best.pt --data data/gs_large.npz
}

run_large_v3() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\large_v3  (2026-06-26)

    echo "=== large_v3 ==="
    python -m gs_pino.train \
    --modes1 32 \
    --modes2 32 \
    --width 64 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --axis-weight 0 \
    --clip-grad 1 \
    --accum-steps 2 \
    --no-amp \
    --seed 0 \
    --epochs 200 \
    --batch-size 8 \
    --lr 0.0005 \
    --data 'data/gs_large2k.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v3
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v3/best.pt --data data/gs_large2k.npz
}

run_large_v4() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\large_v4  (2026-06-30)

    echo "=== large_v4 ==="
    python -m gs_pino.train \
    --modes1 32 \
    --modes2 32 \
    --width 64 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --axis-weight 0 \
    --clip-grad 1 \
    --accum-steps 2 \
    --no-amp \
    --warmup-epochs 5 \
    --patience 50 \
    --min-epochs 50 \
    --seed 0 \
    --epochs 200 \
    --batch-size 8 \
    --lr 0.0005 \
    --data 'data/gs_large2k.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v4
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v4/best.pt --data data/gs_large2k.npz
}

run_large_v4.1() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\large_v4.1  (2026-07-17)

    echo "=== large_v4.1 ==="
    python -m gs_pino.train \
    --modes1 16 \
    --modes2 16 \
    --width 32 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --axis-weight 0.01 \
    --clip-grad 1 \
    --accum-steps 2 \
    --no-amp \
    --warmup-epochs 5 \
    --patience 30 \
    --min-epochs 50 \
    --seed 42 \
    --epochs 200 \
    --batch-size 4 \
    --lr 0.001 \
    --data 'data/gs_fixed_boundary_v41.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v4.1
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/large_v4.1/best.pt --data data/gs_fixed_boundary_v41.npz
}

run_v41_fixed() {
    # D:\D_F\Fusion\AI\PINN\GitHub-tests\GS_PINO\outputs\v41_fixed  (2026-07-17)

    echo "=== v41_fixed ==="
    python -m gs_pino.train \
    --modes1 16 \
    --modes2 16 \
    --width 32 \
    --layers 4 \
    --pde-weight 0.01 \
    --bc-weight 0.05 \
    --ip-weight 0 \
    --axis-weight 0.01 \
    --clip-grad 1 \
    --accum-steps 2 \
    --no-amp \
    --warmup-epochs 5 \
    --patience 30 \
    --min-epochs 50 \
    --seed 0 \
    --epochs 100 \
    --batch-size 4 \
    --lr 0.001 \
    --data 'gs_fixed_boundary_v41_clean.npz' \
    --output-dir D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/v41_fixed
    python -m gs_pino.evaluate --checkpoint D:/D_F/Fusion/AI/PINN/GitHub-tests/GS_PINO/outputs/v41_fixed/best.pt --data gs_fixed_boundary_v41_clean.npz
}

if [ $# -gt 0 ]; then
    for exp in "$@"; do
        case "$exp" in
            large) run_large ;;
            large_v2) run_large_v2 ;;
            large_v3) run_large_v3 ;;
            large_v4) run_large_v4 ;;
            large_v4.1) run_large_v4.1 ;;
            v41_fixed) run_v41_fixed ;;
            *) echo "unknown experiment: $exp"; echo "known: large large_v2 large_v3 large_v4 large_v4.1 v41_fixed"; exit 1 ;;
        esac
    done
else
    run_large
    run_large_v2
    run_large_v3
    run_large_v4
    run_large_v4.1
    run_v41_fixed
fi
